morre

diff --git a/.github/workflows/main_flightsquawk.yml b/.github/workflows/main_flightsquawk.yml
--- a/.github/workflows/main_flightsquawk.yml
+++ b/.github/workflows/main_flightsquawk.yml
@@ -51,6 +51,16 @@ jobs:
       - name: Unzip artifact for deployment
         run: unzip release.zip
 
+      - name: Verify Secret Exists
+        
+        run: |
+          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
+            echo "ERROR: The secret is empty or missing!"
+            exit 1
+          else
+            echo "SUCCESS: The secret is populated."
+          fi
+
       - name: 'Deploy to Azure Web App'
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v3
